apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: spring-petclinic
  namespace: aro-ws
spec:
  host:
  to:
    kind: Service
    name: spring-petclinic
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
